apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-django
  labels:
    app: hello-django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-django
  template:
    metadata:
      labels:
        app: hello-django
    spec:
      containers:
      - name: hello-django
        image: quay.io/vguar/hello-world-java
        ports:
        - containerPort: 8080
          name: http
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 15
