apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-django
  name: hello-django
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
    name: http
  selector:
    app: hello-django
  type: LoadBalancer